### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by toddself** [toddself/boxcar#1]
Here's a basic set of functionality that we need before we hit 1.0.
- [x] ability to instantiate a copy
- [x] attach event handers to document to capture events when focus is lost
- [x] make sure focus is applied correctly after each action
- [x] position cursor at end of existing text when editing a cell
- [x] validation function per column
- [x] editor transformation per column
- [x] provide for other input types
  - [x] select
  - [x] checkbox
- [x] filter non-applicable form types
- [x] default styling
  - [x] alternate row colors
  - [x] fix box sizing with focus highlight
- [ ] hook for external function to determine additional styles per row
- [ ] external API
  - [ ] setting/getting data
    - [ ] diff algorithm for applying smart updates to data model
  - [x] getting/setting active cell
  - [ ] getting/setting current edit state
- [x] events feed 
- [ ] computed properties on `state.data`
- [ ] tests 😄 
- [ ] select-by-row
- [ ] copy and paste rows

Future development: 
- [ ] off screen render -- only render what is seen, nothing else
- [ ] drag and drop reordering
- [ ] multi-user mode (operational transform on the data array?)
  - [ ] presence indicator for other active cells
  - [ ] cell-level locking to prevent competing edits
  - [ ] caching of operation or service worker for offline?
